project: 
  type: website
  output-dir: docs
  
website: 
  title: "Lana Hashem Website"
  navbar: 
    left:
      - index.qmd
      - about.qmd
      - dum1.qmd
      - dum2.qmd
format:
  html:
    theme: flatly